function main(){
    if(gamemode===0){
      chance1.visible=true;
      chance2.visible=false;
      if(keyDown("1")&&a2.visible===false&&s2.visible===false){
        a2.visible=true;
        gamemode=1;
        q2.shapeColor=("yellow")
      }
      if(keyDown("2")&&a5.visible===false&&s5.visible===false){
        a5.visible=true;
        gamemode=1;
        q5.shapeColor=("yellow")
      }
      if(keyDown("3")&&a8.visible===false&&s8.visible===false){
        a8.visible=true;
        gamemode=1;
        q8.shapeColor=("yellow")
      }
      if(keyDown("4")&&a1.visible===false&&s1.visible===false){
        a1.visible=true;
        gamemode=1;
        q1.shapeColor=("yellow")
      }
      if(keyDown("5")&&a4.visible===false&&s4.visible===false){
        a4.visible=true;
        gamemode=1;
        q4.shapeColor=("yellow")
      }
      if(keyDown("6")&&a7.visible===false&&s7.visible===false){
        a7.visible=true;
        gamemode=1;
        q7.shapeColor=("yellow")
      }
      if(keyDown("7")&&a3.visible===false&&s3.visible===false){
        a3.visible=true;
        gamemode=1;
        q3.shapeColor=("yellow")
      }
      if(keyDown("8")&&a6.visible===false&&s6.visible===false){
        a6.visible=true;
        gamemode=1;
        q6.shapeColor=("yellow")
      }
      if(keyDown("9")&&a9.visible===false&&s9.visible===false){
        a9.visible=true;
        gamemode=1;
        q9.shapeColor=("yellow")
      }
  
     }
     if(gamemode===1){
      chance2.visible=true;
      chance1.visible=false;
      if(keyDown("1")&&a2.visible===false&&s2.visible===false){
        s2.visible=true;
        gamemode=2;
        q2.shapeColor=("pink")
      }
      if(keyDown("2")&&a5.visible===false&&s5.visible===false){
        s5.visible=true;
        gamemode=2;
        q5.shapeColor=("pink")
      }
      if(keyDown("3")&&a8.visible===false&&s8.visible===false){
        s8.visible=true;
        gamemode=2;
        q8.shapeColor=("pink")
      }
      if(keyDown("4")&&a1.visible===false&&s1.visible===false){
        s1.visible=true;
        gamemode=2;
        q1.shapeColor=("pink")
      }
      if(keyDown("5")&&a4.visible===false&&s4.visible===false){
        s4.visible=true;
        gamemode=2;
        q4.shapeColor=("pink")
      }
      if(keyDown("6")&&a7.visible===false&&s7.visible===false){
        s7.visible=true;
        gamemode=2;
        q7.shapeColor=("pink")
      }
      if(keyDown("7")&&a3.visible===false&&s3.visible===false){
        s3.visible=true;
        gamemode=2;
        q3.shapeColor=("pink")
      }
      if(keyDown("8")&&a6.visible===false&&s6.visible===false){
        s6.visible=true;
        gamemode=2;
        q6.shapeColor=("pink")
      }
      if(keyDown("9")&&a9.visible===false&&s9.visible===false){
        s9.visible=true;
        gamemode=2;
        q9.shapeColor=("pink")
      }
  
     }
     if(gamemode===2){
      chance1.visible=true;
      chance2.visible=false;
      if(keyDown("1")&&a2.visible===false&&s2.visible===false){
        a2.visible=true;
        gamemode=3;
        q2.shapeColor=("yellow")
      }
      if(keyDown("2")&&a5.visible===false&&s5.visible===false){
        a5.visible=true;
        gamemode=3;
        q5.shapeColor=("yellow")
      }
      if(keyDown("3")&&a8.visible===false&&s8.visible===false){
        a8.visible=true;
        gamemode=3;
        q8.shapeColor=("yellow")
      }
      if(keyDown("4")&&a1.visible===false&&s1.visible===false){
        a1.visible=true;
        gamemode=3;
        q1.shapeColor=("yellow")
      }
      if(keyDown("5")&&a4.visible===false&&s4.visible===false){
        a4.visible=true;
        gamemode=3;
        q4.shapeColor=("yellow")
      }
      if(keyDown("6")&&a7.visible===false&&s7.visible===false){
        a7.visible=true;
        gamemode=3;
        q7.shapeColor=("yellow")
      }
      if(keyDown("7")&&a3.visible===false&&s3.visible===false){
        a3.visible=true;
        gamemode=3;
        q3.shapeColor=("yellow")
      }
      if(keyDown("8")&&a6.visible===false&&s6.visible===false){
        a6.visible=true;
        gamemode=3;
        q6.shapeColor=("yellow")
      }
      if(keyDown("9")&&a9.visible===false&&s9.visible===false){
        a9.visible=true;
        gamemode=3;
        q9.shapeColor=("yellow")
      }
  
     }
     if(gamemode===3){
      chance1.visible=false;
      chance2.visible=true;
      if(keyDown("1")&&a2.visible===false&&s2.visible===false){
        s2.visible=true;
        gamemode=4;
        q2.shapeColor=("pink")
      }
      if(keyDown("2")&&a5.visible===false&&s5.visible===false){
        s5.visible=true;
        gamemode=4;
        q5.shapeColor=("pink")
      }
      if(keyDown("3")&&a8.visible===false&&s8.visible===false){
        s8.visible=true;
        gamemode=4;
        q8.shapeColor=("pink")
      }
      if(keyDown("4")&&a1.visible===false&&s1.visible===false){
        s1.visible=true;
        gamemode=4;
        q1.shapeColor=("pink")
      }
      if(keyDown("5")&&a4.visible===false&&s4.visible===false){
        s4.visible=true;
        gamemode=4;
        q4.shapeColor=("pink")
      }
      if(keyDown("6")&&a7.visible===false&&s7.visible===false){
        s7.visible=true;
        gamemode=4;
        q7.shapeColor=("pink")
      }
      if(keyDown("7")&&a3.visible===false&&s3.visible===false){
        s3.visible=true;
        gamemode=4;
        q3.shapeColor=("pink")
      }
      if(keyDown("8")&&a6.visible===false&&s6.visible===false){
        s6.visible=true;
        gamemode=4;
        q6.shapeColor=("pink")
      }
      if(keyDown("9")&&a9.visible===false&&s9.visible===false){
        s9.visible=true;
        gamemode=4;
        q9.shapeColor=("pink")
      }
  
     }
     if(gamemode===4){
      chance1.visible=true;
      chance2.visible=false;
      if(keyDown("1")&&a2.visible===false&&s2.visible===false){
        a2.visible=true;
        gamemode=5;
        q2.shapeColor=("yellow")
      }
      if(keyDown("2")&&a5.visible===false&&s5.visible===false){
        a5.visible=true;
        gamemode=5;
        q5.shapeColor=("yellow")
      }
      if(keyDown("3")&&a8.visible===false&&s8.visible===false){
        a8.visible=true;
        gamemode=5;
        q8.shapeColor=("yellow")
      }
      if(keyDown("4")&&a1.visible===false&&s1.visible===false){
        a1.visible=true;
        gamemode=5;
        q1.shapeColor=("yellow")
      }
      if(keyDown("5")&&a4.visible===false&&s4.visible===false){
        a4.visible=true;
        gamemode=5;
        q4.shapeColor=("yellow")
      }
      if(keyDown("6")&&a7.visible===false&&s7.visible===false){
        a7.visible=true;
        gamemode=5;
        q7.shapeColor=("yellow")
      }
      if(keyDown("7")&&a3.visible===false&&s3.visible===false){
        a3.visible=true;
        gamemode=5;
        q3.shapeColor=("yellow")
      }
      if(keyDown("8")&&a6.visible===false&&s6.visible===false){
        a6.visible=true;
        gamemode=5;
        q6.shapeColor=("yellow")
      }
      if(keyDown("9")&&a9.visible===false&&s9.visible===false){
        a9.visible=true;
        gamemode=5;
        q9.shapeColor=("yellow")
      }
  
     }
     if(gamemode===5){
      chance1.visible=false;
      chance2.visible=true;
      if(keyDown("1")&&a2.visible===false&&s2.visible===false){
        s2.visible=true;
        gamemode=6;
        q2.shapeColor=("pink")
      }
      if(keyDown("2")&&a5.visible===false&&s5.visible===false){
        s5.visible=true;
        gamemode=6;
        q5.shapeColor=("pink")
      }
      if(keyDown("3")&&a8.visible===false&&s8.visible===false){
        s8.visible=true;
        gamemode=6;
        q8.shapeColor=("pink")
      }
      if(keyDown("4")&&a1.visible===false&&s1.visible===false){
        s1.visible=true;
        gamemode=6;
        q1.shapeColor=("pink")
      }
      if(keyDown("5")&&a4.visible===false&&s4.visible===false){
        s4.visible=true;
        gamemode=6;
        q4.shapeColor=("pink")
      }
      if(keyDown("6")&&a7.visible===false&&s7.visible===false){
        s7.visible=true;
        gamemode=6;
        q7.shapeColor=("pink")
      }
      if(keyDown("7")&&a3.visible===false&&s3.visible===false){
        s3.visible=true;
        gamemode=6;
        q3.shapeColor=("pink")
      }
      if(keyDown("8")&&a6.visible===false&&s6.visible===false){
        s6.visible=true;
        gamemode=6;
        q6.shapeColor=("pink")
      }
      if(keyDown("9")&&a9.visible===false&&s9.visible===false){
        s9.visible=true;
        gamemode=6;
        q9.shapeColor=("pink")
      }
  
     }
     if(gamemode===6){
      chance1.visible=true;
      chance2.visible=false;
      if(keyDown("1")&&a2.visible===false&&s2.visible===false){
        a2.visible=true;
        gamemode=7;
        q2.shapeColor=("yellow")
      }
      if(keyDown("2")&&a5.visible===false&&s5.visible===false){
        a5.visible=true;
        gamemode=7;
        q5.shapeColor=("yellow")
      }
      if(keyDown("3")&&a8.visible===false&&s8.visible===false){
        a8.visible=true;
        gamemode=7;
        q8.shapeColor=("yellow")
      }
      if(keyDown("4")&&a1.visible===false&&s1.visible===false){
        a1.visible=true;
        gamemode=7;
        q1.shapeColor=("yellow")
      }
      if(keyDown("5")&&a4.visible===false&&s4.visible===false){
        a4.visible=true;
        gamemode=7;
        q4.shapeColor=("yellow")
      }
      if(keyDown("6")&&a7.visible===false&&s7.visible===false){
        a7.visible=true;
        gamemode=7;
        q7.shapeColor=("yellow")
      }
      if(keyDown("7")&&a3.visible===false&&s3.visible===false){
        a3.visible=true;
        gamemode=7;
        q3.shapeColor=("yellow")
      }
      if(keyDown("8")&&a6.visible===false&&s6.visible===false){
        a6.visible=true;
        gamemode=7;
        q6.shapeColor=("yellow")
      }
      if(keyDown("9")&&a9.visible===false&&s9.visible===false){
        a9.visible=true;
        gamemode=7;
        q9.shapeColor=("yellow")
      }
  
     }
     if(gamemode===7){
      chance1.visible=false;
      chance2.visible=true;
      if(keyDown("1")&&a2.visible===false&&s2.visible===false){
        s2.visible=true;
        gamemode=8;
        q2.shapeColor=("pink")
      }
      if(keyDown("2")&&a5.visible===false&&s5.visible===false){
        s5.visible=true;
        gamemode=8;
        q5.shapeColor=("pink")
      }
      if(keyDown("3")&&a8.visible===false&&s8.visible===false){
        s8.visible=true;
        gamemode=8;
        q8.shapeColor=("pink")
      }
      if(keyDown("4")&&a1.visible===false&&s1.visible===false){
        s1.visible=true;
        gamemode=8;
        q1.shapeColor=("pink")
      }
      if(keyDown("5")&&a4.visible===false&&s4.visible===false){
        s4.visible=true;
        gamemode=8;
        q4.shapeColor=("pink")
      }
      if(keyDown("6")&&a7.visible===false&&s7.visible===false){
        s7.visible=true;
        gamemode=8;
        q7.shapeColor=("pink")
      }
      if(keyDown("7")&&a3.visible===false&&s3.visible===false){
        s3.visible=true;
        gamemode=8;
        q3.shapeColor=("pink")
      }
      if(keyDown("8")&&a6.visible===false&&s6.visible===false){
        s6.visible=true;
        gamemode=8;
        q6.shapeColor=("pink")
      }
      if(keyDown("9")&&a9.visible===false&&s9.visible===false){
        s9.visible=true;
        gamemode=8;
        q9.shapeColor=("pink")
      }
  
     }
     if(gamemode===8){
      chance1.visible=true;
      chance2.visible=false;
      if(keyDown("1")&&a2.visible===false&&s2.visible===false){
        a2.visible=true;
        gamemode=9;
        q2.shapeColor=("yellow")
      }
      if(keyDown("2")&&a5.visible===false&&s5.visible===false){
        a5.visible=true;
        gamemode=9;
        q5.shapeColor=("yellow")
      }
      if(keyDown("3")&&a8.visible===false&&s8.visible===false){
        a8.visible=true;
        gamemode=9;
        q8.shapeColor=("yellow")
      }
      if(keyDown("4")&&a1.visible===false&&s1.visible===false){
        a1.visible=true;
        gamemode=9;
        q1.shapeColor=("yellow")
      }
      if(keyDown("5")&&a4.visible===false&&s4.visible===false){
        a4.visible=true;
        gamemode=9;
        q4.shapeColor=("yellow")
      }
      if(keyDown("6")&&a7.visible===false&&s7.visible===false){
        a7.visible=true;
        gamemode=9;
        q7.shapeColor=("yellow")
      }
      if(keyDown("7")&&a3.visible===false&&s3.visible===false){
        a3.visible=true;
        gamemode=9;
        q3.shapeColor=("yellow")
      }
      if(keyDown("8")&&a6.visible===false&&s6.visible===false){
        a6.visible=true;
        gamemode=9;
        q6.shapeColor=("yellow")
      }
      if(keyDown("9")&&a9.visible===false&&s9.visible===false){
        a9.visible=true;
        gamemode=9;
        q9.shapeColor=("yellow")
      }
  
     }
  }